# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Beckett
email: jonathan.beckett@gmail.com
description: >-
  Welcome to my homepage on the internet.

# Repository settings for GitHub Pages
repository: jonbeckett/jonbeckett.github.io
url: "https://jonbeckett.github.io"
baseurl: ""

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

# Minimal Mistakes settings
author:
  name: "Jonathan Beckett"
  bio: "Welcome to my homepage on the internet."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonbeckett"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - archive/