theme: jekyll-theme-minimal

title: jonbeckett.github.io
description: The online homepage of Jonathan Beckett

logo: https://pbs.twimg.com/profile_images/1292438303757787136/f0LbZue9_200x200.jpg
show_downloads: false
