# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Beckett
email: jonathan.beckett@gmail.com
description: >-
  Welcome to my homepage on the internet.

# Repository settings for GitHub Pages
repository: jonbeckett/jonbeckett.github.io
url: "https://jonbeckett.github.io"
baseurl: ""

# Build settings
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Pagination settings
paginate: 10
paginate_path: /page:num/

# Minimal Mistakes settings
minimal_mistakes_skin: default
locale: "en-US"
title_separator: "-"

# Site Author
author:
  name: "Jonathan Beckett"
  avatar: ""
  bio: "Welcome to my homepage on the internet."
  location: ""
  email: "jonathan.beckett@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonbeckett"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonbeckett"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - archive/